# Generated by Django 2.0.4 on 2018-05-17 12:54

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180517_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='GMT+1', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
