# Generated by Django 2.0.4 on 2018-05-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='instructions',
        ),
        migrations.AddField(
            model_name='blog',
            name='ingredients',
            field=models.CharField(default='what do you want to put in your cake?', max_length=100),
            preserve_default=False,
        ),
    ]
