# Generated by Django 2.0.4 on 2018-05-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180524_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='instructions',
            new_name='blog',
        ),
    ]
