# Generated by Django 2.0.4 on 2018-06-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180524_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(),
        ),
    ]
