# Generated by Django 2.0.4 on 2018-06-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='ingredients',
            new_name='description',
        ),
    ]
