# Generated by Django 2.0.4 on 2018-06-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180612_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='item_photo',
            field=models.ImageField(default=0, upload_to='static'),
            preserve_default=False,
        ),
    ]
