# Generated by Django 2.0.4 on 2018-06-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ingredients',
            field=models.TextField(default=1, verbose_name=list),
            preserve_default=False,
        ),
    ]
