# Generated by Django 2.0.4 on 2018-06-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='item_photo',
        ),
        migrations.AddField(
            model_name='blog',
            name='thumb',
            field=models.ImageField(default='default.png', upload_to='static'),
        ),
    ]
