# Generated by Django 2.0.4 on 2018-06-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180618_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='thumb',
            new_name='item_photo',
        ),
    ]
