# Generated by Django 2.0.4 on 2018-06-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180618_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='item_photo',
            field=models.ImageField(default='default.png', upload_to='media'),
        ),
    ]
